export const daysOfWeek = {
    sun: 'Sunday',
    mon: 'Monday',
    tue: 'Tuesday',
    wed: 'Wednesday',
    thur: 'Thursday',
    fri: 'Friday',
    sat: 'Saturday',
}

export const repeats = {
    weekly: 'Weekly',
    monthly: 'Monthly',
    daily: 'Daily',
}

export const lineIcons = [
    'sprucebot',
    'add-circle',
    'chevron-left',
    'document-text',
    'link-angle',
    'play-circle',
    'star',
    'add-square',
    'chevron-right',
    'download-cloud',
    'link-flat',
    'present',
    'sun',
    'add',
    'chevron-up',
    'download',
    'loader',
    'refresh-circle',
    'tag',
    'alarm',
    'clipboard',
    'edit-box',
    'location-pin',
    'refresh',
    'time',
    'arrow-back',
    'clock',
    'edit-line',
    'lock',
    'repeat',
    'tool',
    'arrow-down-circle',
    'close-circle',
    'email',
    'map',
    'restricted',
    'trending-down',
    'arrow-down',
    'close-square',
    'emoji-happy',
    'message-circle',
    'rotate',
    'trending-up',
    'arrow-next',
    'close',
    'emoji-sad',
    'message-square',
    'search-no',
    'triangle',
    'arrow-up-circle',
    'code',
    'external-link',
    'mic-off',
    'search',
    'unlock',
    'arrow-up',
    'coffee',
    'fav-heart',
    'mic-on',
    'selector-checked',
    'upload-cloud',
    'attachment',
    'command',
    'flag',
    'minus-circle',
    'selector-circle-filled',
    'upload',
    'award-badge',
    'corner-down-left',
    'flip-01',
    'minus-square',
    'selector-circle',
    'user-add',
    'binoculars',
    'corner-down-right',
    'flip-02',
    'money-sign',
    'send',
    'user-delete',
    'bolt',
    'corner-left-down',
    'folder',
    'more-horizontal',
    'settings-filled',
    'user',
    'book-open',
    'corner-left-up',
    'globe',
    'more-vertical',
    'settings',
    'users',
    'book',
    'corner-right-down',
    'hash-tag',
    'notification-off',
    'share',
    'video-off',
    'bookmark',
    'corner-right-up',
    'headphones',
    'notification-on',
    'shopping-bag',
    'video',
    'calendar-add',
    'corner-up-left',
    'help-buoy',
    'object',
    'shopping-cart',
    'warning',
    'calendar',
    'corner-up-right',
    'help-circle',
    'pause-circle',
    'sort-filter-down',
    'wifi',
    'camera',
    'crop',
    'home',
    'phone-unavailable',
    'sort-filter-up',
    'zoom-in',
    'cellphone',
    'delete',
    'info',
    'phone',
    'sound-off',
    'zoom-out',
    'checkmark',
    'document-blank',
    'jump',
    'photo',
    'sound-on',
    'chevron-down',
    'document-new',
    'layers',
    'picked',
    'star-filled',
] as const

export const lineIconChoices = lineIcons.map((i) => ({
    value: i,
    label: i,
}))

export const eventStyles = [
    'draft',
    'tentative',
    'upcoming',
    'unavailable',
    'blocked',
    'active',
    'past',
    'warn',
    'critical',
]

const eventLabels = [
    'Draft',
    'Tentative',
    'Upcoming',
    'Unavailable',
    'Blocked',
    'Active',
    'Past',
    'Warning',
    'Critical',
]

export const eventStyleChoices = eventStyles.map((i, idx) => ({
    value: i,
    label: eventLabels[idx],
}))
